# TCL File Generated by Component Editor 20.1
# Wed Sep 18 20:58:47 AEST 2024
# DO NOT MODIFY


# 
# data_expander "data_expander" v1.0
#  2024.09.18.20:58:47
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module data_expander
# 
set_module_property DESCRIPTION ""
set_module_property NAME data_expander
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME data_expander
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL data_expander
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file data_expander.sv SYSTEM_VERILOG PATH data_expander.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter INTIAL_DATA_WIDTH INTEGER 12
set_parameter_property INTIAL_DATA_WIDTH DEFAULT_VALUE 12
set_parameter_property INTIAL_DATA_WIDTH DISPLAY_NAME INTIAL_DATA_WIDTH
set_parameter_property INTIAL_DATA_WIDTH TYPE INTEGER
set_parameter_property INTIAL_DATA_WIDTH UNITS None
set_parameter_property INTIAL_DATA_WIDTH HDL_PARAMETER true
add_parameter FINAL_DATA_WIDTH INTEGER 30
set_parameter_property FINAL_DATA_WIDTH DEFAULT_VALUE 30
set_parameter_property FINAL_DATA_WIDTH DISPLAY_NAME FINAL_DATA_WIDTH
set_parameter_property FINAL_DATA_WIDTH TYPE INTEGER
set_parameter_property FINAL_DATA_WIDTH UNITS None
set_parameter_property FINAL_DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 4
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink data_in data Input INTIAL_DATA_WIDTH
add_interface_port avalon_streaming_sink eop_in endofpacket Input 1
add_interface_port avalon_streaming_sink sop_in startofpacket Input 1
add_interface_port avalon_streaming_sink valid_in valid Input 1
add_interface_port avalon_streaming_sink ready_out ready Output 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 10
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source data_out data Output FINAL_DATA_WIDTH
add_interface_port avalon_streaming_source eop_out endofpacket Output 1
add_interface_port avalon_streaming_source sop_out startofpacket Output 1
add_interface_port avalon_streaming_source valid_out valid Output 1
add_interface_port avalon_streaming_source ready_in ready Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1

